project
fortuna91/ya_praktikum_final pull request #1
Opened 2022-06-16 19:21 UTC by fortuna91

2022-06-19 14:48 UTC, Bazys requested changes
пара замечаний

2022-06-19 14:48 UTC, Bazys commented on internal/db/credefs.go
> +package db
очень рекомендую использовать какой нить мигратор, типа:
1. [goose](https://pressly.github.io/goose/)
2. [migrate](https://github.com/golang-migrate/migrate)
там есть вариант встраивания в код.

2022-06-19 14:48 UTC, Bazys commented on internal/db/db.go
> +type UserData struct {
эти все структуры лучше вынести в модуль Entity
и в названии Data лишнее, особенно если это все будет в отдельном модуле

2022-06-19 14:48 UTC, Bazys commented on internal/accrual/accrual.go
> +	if response.StatusCode == 429 {
```suggestion
	if response.StatusCode == http.StatusTooManyRequests {
```
предлагаю пользоваться стандартными константами

2022-06-19 14:48 UTC, Bazys commented on internal/accrual/accrual.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
почему именно 2 секунды?
почему бы не вынести в конфиг и хотя бы в одном месте хардкодить?

2022-06-19 14:48 UTC, Bazys commented on internal/accrual/accrual.go
> +	fmt.Printf("Get order from accrual system %v\n", order)
очень рекомендую начать пользоваться логерами типа [zap](https://github.com/uber-go/zap) или [zerolog](https://github.com/rs/zerolog)

2022-06-19 14:48 UTC, Bazys commented on internal/accrual/accrual.go
> +		status = PROCESSING
уверена что надо за чужую систему решать, в каком статусе находится заказ?

2022-06-19 14:48 UTC, Bazys commented on internal/accrual/accrual.go
> +	newBalance := balance.Current + order.Accrual
я бы увеличение делал на уровне SQL. меньше вероятность обновить данные которые обновлены в другом потоке.

2022-06-19 14:48 UTC, Bazys commented on internal/accrual/accrual.go
> +type QueueAccrualSystem struct {
а с chan можно не городить свои методы Pop и не заморачиваться с мютексами

2022-06-19 14:48 UTC, Bazys commented on internal/auth/auth.go
> +var tokenDuration = 1 * time.Hour
очень нехорошо, когда всякие такие "магические" константы раскиданы по всему коду.

2022-06-19 14:48 UTC, Bazys commented on internal/configs/configs.go
> +func SetServerConfig() ServerConfig {
да, я так и не донес свой посыл видимо.
если сначала читать флаги командной строки, а затем парсить энвы, то не нужны будут ифы с 28 строки

2022-06-19 14:48 UTC, Bazys commented on internal/db/db.go
> +	if err != nil {
а может лучше возращать ошибку, а уж паниковать в main?
потому что если потом где то появится recover то факт того что не подключились к БД может и не обнаружится.

2022-06-19 14:48 UTC, Bazys commented on internal/db/db.go
> +	Accrual    float32   `json:"accrual,omitempty"`
если уж и использовать float для денег, то лучше float64 - меньше погрешность.
а в принципе надо хранить в копейках и перед выводом делить на 100

2022-06-19 14:48 UTC, Bazys commented on internal/db/db.go
> +func (db *DBStorage) GetWithdrawals(ctx context.Context, userID int64) []WithdrawalsData {
может все таки возвращать ошибку?
как 500тки отдавать и алерты настраивать?

2022-06-19 14:48 UTC, Bazys commented on internal/handlers/handlers.go
> +var DB *db.DBStorage
публичная гллобальная переменная, точно так?
а если случайно из другого модуля изменится?
структуру с двумя этими переменными и конструктор, который принимает их и возвращает интерфейс с методами хэндлера?

2022-06-19 14:48 UTC, Bazys commented on internal/utils/utils.go
> +package utils
1. название utils, такое никому ни о чём не говорит, желательно более информативное
2. а точно нужен целый модуль ради одной функции?

2022-06-20 10:29 UTC, fortuna91 commented on internal/accrual/accrual.go
> +		status = PROCESSING
как ТЗ написано... В ТЗ нет у заказа статуса REGISTERED

2022-06-20 10:32 UTC, fortuna91 commented on internal/configs/configs.go
> +func SetServerConfig() ServerConfig {
это потому что в ТЗ прошлых заданий был обсолютно дурацкий приоритет переменных перед конфигом

2022-06-20 10:35 UTC, fortuna91 commented on internal/db/db.go
> +	Accrual    float32   `json:"accrual,omitempty"`
У меня и было 64, но в тестах я увидела, что используется 32. И чтобы не было неожиданных погрешностей, я перешла на 32. Там в целом система возвращает странные нереалистичные цифры

2022-06-20 13:57 UTC, fortuna91 commented on internal/utils/utils.go
> +package utils
Ну ей просто больше не нашлось другого логичного места. Я ее вызываю из 2х разных модулей

2022-06-21 12:27 UTC, fortuna91 commented on internal/db/credefs.go
> +package db
Почитала, мне сейчас кажется это оверхэдом, чисто для кредефов. Но я буду иметь ввиду, спасибо

2022-06-22 10:07 UTC, Bazys approved these changes

2022-06-23 11:55 UTC, merged